### PR TITLE
Add TLS/SSL support to the Netty transport

### PR DESCRIPTION
**Pull request by electrical**
This PR adds TLS/SSL support to the netty transport
It uses java keystore (JKS) files for storing the keys

### CODE REVIEW

**Comment by electrical** [comment]
I'm sure there is some stuff that can be cleaned up so please review :-)

**Comment by electrical** [comment]
Most likely failed because of cert hostname issues because the hostname is different on travis then on my dev system.
Should we disable the test?

**Comment by electrical** [comment]
Making some modifications to see if i can make the test pass. Will squash commits eventually.

**Comment by electrical** [comment]
Test passes because i disabled it. Works on my local system. Unsure how i can generate a cert that would work on travis without re-generating one on the fly.

**Comment by electrical** [comment]
Tried several things but didn't make it work :-( submitting for now without active test.

**Comment by kuujo** [comment]
Hmmm.... Yeah I'm not sure how you would go about that either. It's all good :-)

**Comment by kuujo** [comment]
This is awesome!

I wonder if we should call SSL properties like `sslTruststorePath` -> `ssl.trustStorePath` to separate the SSL configuration. In Atomix, the properties file would then become:

```
replica.transport.ssl.enabled=true
replica.transport.ssl.trustStorePath=/some/where
replica.transport.ssl.trustStorePassword=someThing
```

**Comment by electrical** [comment]
Ahh okay. I didn't know that having the names there would result it in being exposed in atomix as well.
It does make sense yeah to have dots in them. Will modify that.

**Comment by electrical** [comment]
I might make it a little bit more verbose like 'ssl.truststore.path'

**Comment by kuujo** [comment]
Yeah I think that sounds good too

**Pull request merged**
